# Generated by Django 5.0 on 2025-05-01 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='lesson',
            name='content_type',
            field=models.CharField(choices=[('video', 'Video'), ('book', 'Book'), ('file', 'File')], default='file', max_length=10),
        ),
        migrations.AddField(
            model_name='lesson',
            name='subject',
            field=models.CharField(default='General', max_length=100),
        ),
    ]
