# Generated by Django 5.0 on 2025-05-01 08:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_lesson_options_lesson_content_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='duration',
        ),
        migrations.AddField(
            model_name='lesson',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='lesson_files/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'docx', 'mp4', 'txt'])]),
        ),
    ]
